APP_INTERFACE = 'tcp://127.0.0.1:5555'
DEFAULT_LIBRARY = 'mongodb://127.0.0.1/apps'
DEFAULT_COLLECTION = 'apps'

ERROR_SUCCESS = 0
ERROR_EXCEPTION = 1

METHOD_REGISTER = 'Register'
METHOD_UNREGISTER = 'UnRegister'
METHOD_UPDATE = 'Update'
METHOD_QUERY = 'Query'
